/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SalaryGuidesRouteImport } from './routes/salary-guides'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HiringGuidesRouteImport } from './routes/hiring-guides'
import { Route as DiscoveryExperienceRouteImport } from './routes/discovery-experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtlasMethodRouteImport } from './routes/atlas-method'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasLibraryTalentLensRouteImport } from './routes/atlas-library.talent-lens'
import { Route as AtlasLibrarySearchBlueprintRouteImport } from './routes/atlas-library.search-blueprint'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryGuidesRoute = SalaryGuidesRouteImport.update({
  id: '/salary-guides',
  path: '/salary-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringGuidesRoute = HiringGuidesRouteImport.update({
  id: '/hiring-guides',
  path: '/hiring-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryExperienceRoute = DiscoveryExperienceRouteImport.update({
  id: '/discovery-experience',
  path: '/discovery-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasMethodRoute = AtlasMethodRouteImport.update({
  id: '/atlas-method',
  path: '/atlas-method',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasLibraryTalentLensRoute = AtlasLibraryTalentLensRouteImport.update({
  id: '/atlas-library/talent-lens',
  path: '/atlas-library/talent-lens',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasLibrarySearchBlueprintRoute =
  AtlasLibrarySearchBlueprintRouteImport.update({
    id: '/atlas-library/search-blueprint',
    path: '/atlas-library/search-blueprint',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/mcp': typeof McpRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/atlas-library/search-blueprint': typeof AtlasLibrarySearchBlueprintRoute
  '/atlas-library/talent-lens': typeof AtlasLibraryTalentLensRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/mcp': typeof McpRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/atlas-library/search-blueprint': typeof AtlasLibrarySearchBlueprintRoute
  '/atlas-library/talent-lens': typeof AtlasLibraryTalentLensRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/mcp': typeof McpRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/atlas-library/search-blueprint': typeof AtlasLibrarySearchBlueprintRoute
  '/atlas-library/talent-lens': typeof AtlasLibraryTalentLensRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/mcp'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/atlas-library/search-blueprint'
    | '/atlas-library/talent-lens'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/mcp'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/atlas-library/search-blueprint'
    | '/atlas-library/talent-lens'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/mcp'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/atlas-library/search-blueprint'
    | '/atlas-library/talent-lens'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasMethodRoute: typeof AtlasMethodRoute
  ContactRoute: typeof ContactRoute
  DiscoveryExperienceRoute: typeof DiscoveryExperienceRoute
  HiringGuidesRoute: typeof HiringGuidesRoute
  IndustriesRoute: typeof IndustriesRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  McpRoute: typeof McpRoute
  SalaryGuidesRoute: typeof SalaryGuidesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AtlasLibrarySearchBlueprintRoute: typeof AtlasLibrarySearchBlueprintRoute
  AtlasLibraryTalentLensRoute: typeof AtlasLibraryTalentLensRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-guides': {
      id: '/salary-guides'
      path: '/salary-guides'
      fullPath: '/salary-guides'
      preLoaderRoute: typeof SalaryGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-guides': {
      id: '/hiring-guides'
      path: '/hiring-guides'
      fullPath: '/hiring-guides'
      preLoaderRoute: typeof HiringGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery-experience': {
      id: '/discovery-experience'
      path: '/discovery-experience'
      fullPath: '/discovery-experience'
      preLoaderRoute: typeof DiscoveryExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-method': {
      id: '/atlas-method'
      path: '/atlas-method'
      fullPath: '/atlas-method'
      preLoaderRoute: typeof AtlasMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-library/talent-lens': {
      id: '/atlas-library/talent-lens'
      path: '/atlas-library/talent-lens'
      fullPath: '/atlas-library/talent-lens'
      preLoaderRoute: typeof AtlasLibraryTalentLensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-library/search-blueprint': {
      id: '/atlas-library/search-blueprint'
      path: '/atlas-library/search-blueprint'
      fullPath: '/atlas-library/search-blueprint'
      preLoaderRoute: typeof AtlasLibrarySearchBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasMethodRoute: AtlasMethodRoute,
  ContactRoute: ContactRoute,
  DiscoveryExperienceRoute: DiscoveryExperienceRoute,
  HiringGuidesRoute: HiringGuidesRoute,
  IndustriesRoute: IndustriesRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  McpRoute: McpRoute,
  SalaryGuidesRoute: SalaryGuidesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AtlasLibrarySearchBlueprintRoute: AtlasLibrarySearchBlueprintRoute,
  AtlasLibraryTalentLensRoute: AtlasLibraryTalentLensRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
