/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SalaryGuidesRouteImport } from './routes/salary-guides'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HiringGuidesRouteImport } from './routes/hiring-guides'
import { Route as DiscoveryExperienceRouteImport } from './routes/discovery-experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtlasMethodRouteImport } from './routes/atlas-method'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryGuidesRoute = SalaryGuidesRouteImport.update({
  id: '/salary-guides',
  path: '/salary-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringGuidesRoute = HiringGuidesRouteImport.update({
  id: '/hiring-guides',
  path: '/hiring-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryExperienceRoute = DiscoveryExperienceRouteImport.update({
  id: '/discovery-experience',
  path: '/discovery-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasMethodRoute = AtlasMethodRouteImport.update({
  id: '/atlas-method',
  path: '/atlas-method',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-method': typeof AtlasMethodRoute
  '/contact': typeof ContactRoute
  '/discovery-experience': typeof DiscoveryExperienceRoute
  '/hiring-guides': typeof HiringGuidesRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/salary-guides': typeof SalaryGuidesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas-method'
    | '/contact'
    | '/discovery-experience'
    | '/hiring-guides'
    | '/industries'
    | '/knowledge-hub'
    | '/salary-guides'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasMethodRoute: typeof AtlasMethodRoute
  ContactRoute: typeof ContactRoute
  DiscoveryExperienceRoute: typeof DiscoveryExperienceRoute
  HiringGuidesRoute: typeof HiringGuidesRoute
  IndustriesRoute: typeof IndustriesRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  SalaryGuidesRoute: typeof SalaryGuidesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-guides': {
      id: '/salary-guides'
      path: '/salary-guides'
      fullPath: '/salary-guides'
      preLoaderRoute: typeof SalaryGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-guides': {
      id: '/hiring-guides'
      path: '/hiring-guides'
      fullPath: '/hiring-guides'
      preLoaderRoute: typeof HiringGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery-experience': {
      id: '/discovery-experience'
      path: '/discovery-experience'
      fullPath: '/discovery-experience'
      preLoaderRoute: typeof DiscoveryExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-method': {
      id: '/atlas-method'
      path: '/atlas-method'
      fullPath: '/atlas-method'
      preLoaderRoute: typeof AtlasMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasMethodRoute: AtlasMethodRoute,
  ContactRoute: ContactRoute,
  DiscoveryExperienceRoute: DiscoveryExperienceRoute,
  HiringGuidesRoute: HiringGuidesRoute,
  IndustriesRoute: IndustriesRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  SalaryGuidesRoute: SalaryGuidesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
